----------------------------------------------RELATORIO AFASTAMENTO-------------------------------------------------------------

SELECT T1.R8_MAT 'MATRICULA', T2.RA_NOME 'NOME', T2.RA_CC ' CODIGO CENTRO DE CUSTO', T3.CTT_DESC01 'CENTRO DE CUSTO', CAST (T1.R8_DATAINI as DATE) 'DATA', R8_TIPOAFA 'TIPO AFASTAMENTO', T5.RCM_DESCRI 'DESCRICAO AFASTAMENTO', R8_DPAGAR 'DIAS A PAGAR', R8_CID 'CID', T4.TMR_DOENCA 'DESCRICAO CID' 
FROM SR8050 T1

LEFT JOIN SRA050 T2 ON T2.RA_MAT = T1.R8_MAT AND  T2.D_E_L_E_T_ = ''
INNER JOIN CTT010 T3 ON T2.RA_CC = T3.CTT_CUSTO AND T3.D_E_L_E_T_ = ''
LEFT JOIN TMR050 T4 ON T1.R8_CID = T4.TMR_CID AND T4.D_E_L_E_T_ = ''
INNER JOIN RCM050 T5 ON T1.R8_TIPOAFA = T5.RCM_TIPO AND T5.D_E_L_E_T_ = ''

WHERE T1.R8_DATAINI >= '20230101' AND T1.D_E_L_E_T_ = ''
ORDER BY R8_DATAINI, RA_NOME
