SELECT T1.PC_MAT 'MATRICULA', T2.RA_NOME 'NOME', CAST (T1.PC_DATA as DATE) 'DATA', T3.CTT_DESC01 'CENTRO DE CUSTO', T1.PC_ABONO 'TIPO ABONO', T1.PC_QTABONO 'HORAS' -- * 
FROM SPC050 T1 
INNER JOIN SRA050 T2 ON T1.PC_MAT = RA_MAT AND T2.D_E_L_E_T_ = ''
INNER JOIN CTT010 T3 ON T2.RA_CC = T3.CTT_CUSTO AND T3.D_E_L_E_T_ = ''
WHERE T1.PC_DATA >= '20230101' AND T1.PC_ABONO = '001' AND T1.D_E_L_E_T_ = ''
ORDER BY PC_DATA, RA_NOME
