Declare @DC_CBO Varchar(MAX)

SELECT 

Q3_CARGO CARGO, 
Q3_DESCSUM DESC_SUMARIA, 
A.TEXTO DESC_CBO,
B.TEXTO DS_DETALHADA,
D.TEXTO Treinamentos,
C.TEXTO Habilidades,
Q3_CBO CBO

FROM 

SQ3010

INNER JOIN (SELECT  RDY_CHAVE, RDY_CAMPO, REPLACE(LTRIM(RTRIM(STRING_AGG(CAST (RDY_TEXTO as varchar(MAX)), CHAR(10)))), '  ', '') TEXTO 
			FROM RDY050 
			GROUP BY RDY_CHAVE, RDY_CAMPO) A ON A.RDY_CHAVE = SQ3010.Q3_DESCDET AND A.RDY_CAMPO = 'Q3_DESCDET'


INNER JOIN (SELECT  RDY_CHAVE, RDY_CAMPO,  REPLACE(LTRIM(RTRIM(STRING_AGG(CAST (RDY_TEXTO as varchar(MAX)), CHAR(10)))), '  ', '') TEXTO 
			FROM RDY050 
			GROUP BY RDY_CHAVE, RDY_CAMPO) B ON B.RDY_CHAVE = SQ3010.Q3_DRESP AND B.RDY_CAMPO = 'Q3_DRESP'

INNER JOIN (SELECT  RDY_CHAVE, RDY_CAMPO,  REPLACE(LTRIM(RTRIM(STRING_AGG(CAST (RDY_TEXTO as varchar(MAX)), CHAR(10)))), '  ', '') TEXTO 
			FROM RDY050 
			GROUP BY RDY_CHAVE, RDY_CAMPO) D ON D.RDY_CHAVE = SQ3010.Q3_DRELINT AND D.RDY_CAMPO = 'Q3_DRELINT'

INNER JOIN (SELECT  RDY_CHAVE, RDY_CAMPO,  REPLACE(LTRIM(RTRIM(STRING_AGG(CAST (RDY_TEXTO as varchar(MAX)), CHAR(10)))), '  ', '') TEXTO  
			FROM RDY050 
			GROUP BY RDY_CHAVE, RDY_CAMPO) C ON C.RDY_CHAVE = SQ3010.Q3_DHABILI AND C.RDY_CAMPO = 'Q3_DHABILI'
ORDER BY Q3_CARGO
